config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'

  get 'profiles/show'

  get 'tweets/index'

  get 'tweets/show'

  get 'tweets/edit'

  get 'tweets/new'

  get 'profiles/:id' => 'profiles#show', as: :profile

  get 'profiles' => 'profiles#index'

  get 'tweets/_form'

  devise_for :users

  resources :tweets

  root "tweets#index"

  resources :relationships

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  #This is the user that initiates action
  belongs_to :user
  #This is the user being followed
  belongs_to :friend,class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :message, presence:true, length: { maximum: 140, too_long: "A tweet can only be 140 characters, max. Everybody knows that! " }
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence:true, uniqueness:true 

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships 

  has_many :inverse_relationships, class_name: "Relationship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_relationships, source: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters

      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit( {roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :location ) }

      devise_parameter_sanitizer.for(:account_update) { |u| u.permit( :email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location ) }

    end
  end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    #This set @users to every user in our database
    @users = User.all
  end

  def show
    #This ser @user to a user based on their id
    @user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # POST /relationships
  # POST /relationships.json
  
  def create
    @relationship = current_user.relationships.build(:friend_id => params[:friend_id])
    if @relationship.save
      flash[:notice] = "Followed successfully."
      redirect_to profile_path(current_user.id)
    else
      flash[:notice] = "Unable to follow."
      redirect_to root_path
    end
  end

  def destroy
    @relationship = current_user.relationships.find(:friend_id => params[:id])
    @relationship.destroy
    flash[:notice] = "No longer following."
    redirect_to profile_path(current_user.id)
  end


  private

  def relationships_params 
    params.require(:relationship).permit(:user_ud), :friend_id) 

  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :udate, :destroy]
  before_filter :authenticate_user!

  def index
    @tweets = Tweet.all
  end

  def show
  end

  def edit
  end

  def new
    @tweet = Tweet.new
  end

  def _form
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.'}
      else 
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
        if @tweet.update(tweet_params)
          format.html{ redirect_to @tweet, notice: 'Tweet was successfully updates.' } 
        else
          format.html (render :edit)
        end
      end
  end

def destroy 
  @tweet.destroy

  respond_to do |format|
    format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
    end
  end

  private

    def set_tweet
      @tweet =Tweet.find(params[:id])
  end
    def tweet_params
      params.require(:tweet).permit(:message, :user_id_id)  
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="container-fluid">
<%=link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-xs" %>

<%= yield %>

</body>
</html>

app/views/profiles/index.html.erb
<h1>User Directory</h1>

<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %><br>
<% end %>

app/views/profiles/show.html.erb
<div class="row">
  <div class= "col-xs-4">
  <h3><%= @user.name %></h3>
  <h5><%= @user.username %></h5>
  <h5><p><%= @user.bio %></p></h5>
  <h5><%= @user.location %></h5>
  <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

  <%= @user.relationships.count %> Following
  <br />
  <% @user.relationships.each do |relationship| %>
    <%=link_to relationship.friend.name, profile_path(relationship.friend) %>
  <%end%>
  <br />
  <br />
  <%= pluralize(@user.inverse_relationships.count, "Follower") %>.
  <br />
  <% @user.inverse_friends.each do |friend| %>
    <%=link_to friend.name, profile_path(friend) %> <br />
  <%end%>
  </div>

  <div class= "col-xs-7">
    <div class="panel panel-default">
      <% @user.tweets.each do |tweet| %>
        <div class="panel-body">
          <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
          <br />
          <br />
          <%= tweet.message %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br />
<br />
<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete %>
  <% else %>
    <%= link_to "Follow", relationships_path(:friend_id => @user), method: :post %>
  <% end %>
<% end %>

<h1><%= @user.username %>'s Profile</h1>

<% @user.tweets.each do |tweet| %>
  <%= tweet.message %><br>
<% end %>

<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to "Unfollow", relationships_path(current_user.relationships.find_by_friend_id(@user), method: :delete ) %>
<% else %>
  <%= link_to "Follow", relationships_path(:friend_id => @user), method: :post %>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>

  <!-- This part checks for errors -->
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:
      </h2>

      <!-- This loops through the errors and shows them as a <ul> -->
      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- This part is the form -->
  <div class="field form-group">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :user_id_id, value: current_user.id %>
  </div>

  <div class="actions form-group">
    <%= f.submit %>
  </div>

<% end %>

app/views/tweets/edit.html.erb
<h1>Editting Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<!-- Our notice, again -->
<p id="notice"><%= notice %></p>

<h1>All The Tweets In The Universe!</h1>

<!-- The table that's going to show our tweets -->
<table>

  <!-- The head of our table -->
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <!-- The body of our table -->
  <tbody>
    
    <!-- Runs through every tweet and puts each one in its own row -->
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user_id_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message: </strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User_id_id: </stong>
    <%= @tweet %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> | 
<%= link_to 'Back', tweets_path %>